version: "3"
services:
  app:
    build: .
    ports:
      - 8082:80
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=0p;/9ol.8ik,
      - MYSQL_DATABASE=blog
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.9.1
#    ports:
#       - 8081:80
#    restart: always
#    environment:
#       - PMA_HOST=mysql

